### ISSUE TITLE
error when trying to incorporate indels onto the snp-patched genome

### ISSUE THREAD

**Issue by tmelia** [churchill-lab/g2gtools#2]
Hi,

I'm trying to use g2gtools to create a pooled transcriptome fasta file to be used with GBRS to map DO mice RNA-Seq data.

I was able to 1) create 8 chain files to map the reference genome to each of the 8 strains and 2) patch the reference genome with strain-specific snps (I did this separately for the 8 founder strains).

However, I got an error, when I tried to incorporate indels to any of the snp-patched genome. I got an error that there is an invalid region: invalid region: start (197194533) > end (103494974)

I am wondering if you can help me out to troubleshoot what's going on. I downloaded all files fresh from the sanger website (ftp://ftp-mouse.sanger.ac.uk/REL-1211-SNPs_Indels and
ftp://ftp-mouse.sanger.ac.uk/ref/NCBIM37_um.fa ). I did filter snps/indels whose quality is not PASS.

update: I was able to run the transform command on chr 1 fasta files. Does it mean there's a particular chromosome that's causing this?

Thanks.

Below are more details

g2gtools vcf2chain -f NCBIM37_um.fa \
-i mgp.v2.indels.annot.reformat.passonly.vcf.gz \
-o ref_to_129S1.chain -s 129S1

g2gtools patch -i NCBIM37_um.fa \
-s 129S1 \
-v mgp.v2.snps.annot.reformat.passonly.vcf.gz \
-o 129S1.snponly.fa 

g2gtools transform -i 129S1.snponly.fa \
-c ref_to_129S1.chain \
-o 129S1.fa

error I got:
pooled_transcriptome]$ g2gtools transform -i 129S1.snponly.fa -c ref_to_129S1.chain -o 129S1.fa
FASTA FILE: /restricted/projectnb/waxmanlab/tisha/DO/pooled_transcriptome/129S1.snponly.fa
CHAIN FILE: /restricted/projectnb/waxmanlab/tisha/DO/pooled_transcriptome/ref_to_129S1.chain
OUTPUT FILE: /restricted/projectnb/waxmanlab/tisha/DO/pooled_transcriptome/129S1.fa
BGZIP: False
REVERSE: False
[fai_load] build FASTA index.
Transforming...
Parsing chain file...
Chain file parsed
Processing chromosome=1
Traceback (most recent call last):
  File "/share/pkg/g2gtools/0.1.29/install/bin/g2gtools.real", line 4, in <module>
    __import__('pkg_resources').run_script('g2gtools==0.1.29', 'g2gtools')
  File "/share/pkg/python/2.7.11/install/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/pkg/python/2.7.11/install/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/share/pkg/g2gtools/0.1.29/install/lib/python2.7/site-packages/g2gtools-0.1.29-py2.7.egg/EGG-INFO/scripts/g2gtools", line 117, in <module>
    G2GToolsApp()
  File "/share/pkg/g2gtools/0.1.29/install/lib/python2.7/site-packages/g2gtools-0.1.29-py2.7.egg/EGG-INFO/scripts/g2gtools", line 75, in __init__
    getattr(self, args.command)()
  File "/share/pkg/g2gtools/0.1.29/install/lib/python2.7/site-packages/g2gtools-0.1.29-py2.7.egg/EGG-INFO/scripts/g2gtools", line 84, in transform
    g2gtools.g2g_commands.command_fasta_transform(sys.argv[2:], self.script_name + ' transform')
  File "/share/pkg/g2gtools/0.1.29/install/lib/python2.7/site-packages/g2gtools-0.1.29-py2.7.egg/g2gtools/g2g_commands.py", line 711, in command_fasta_transform
    fasta_transform(args.fasta, args.chain, all_locations, args.output, args.bgzip, args.reverse)
  File "/share/pkg/g2gtools/0.1.29/install/lib/python2.7/site-packages/g2gtools-0.1.29-py2.7.egg/g2gtools/g2g.py", line 1053, in fasta_transform
    partial_seq = fasta.fetch(location.seqid, last_pos, last_pos + fragment)
  File "pysam/cfaidx.pyx", line 238, in pysam.cfaidx.FastaFile.fetch (pysam/cfaidx.c:3991)
  File "pysam/cutils.pyx", line 206, in pysam.cutils.parse_region (pysam/cutils.c:3486)
ValueError: invalid region: start (197189107) > end (103494974)

**Comment by kbchoi-jax** [comment]
This issue is caused by version mismatch between the reference genome and vcf file.
